# Trial number:      137
# HOTA, MOTA, IDF1:  [55.567]
ocsort:
  asso_func: iou
  conf_thres: 0.5
  delta_t: 3
  det_thresh: 0
  inertia: 0.2
  iou_thresh: 0.3
  max_age: 30
  min_hits: 3
  use_byte: true
